### PR TITLE
Added all the 7.2 stuff released today, including key file

### PR DESCRIPTION
**Pull request by aczid**
Please merge so we have everything in one place.

### CODE REVIEW

**Comment by stefansundin** [comment]
I just want to note something first for the record.

The key file isn't really a new file. It is identical with `TrueCrypt-Foundation-Public-Key.asc`. I figure we should still add it, but it is the same key as before. I suspect that they don't want people to be distracted by "The Foundation" so they renamed the file.

**Comment by stefansundin** [comment]
Only problem with the PR is that the file `TrueCrypt-7.2-source-unix.tar.gz(1).sig` is duplicated. If you delete that one I will merge it. Thanks!

**Comment by stefansundin** [comment]
Okay, to get this in promptly, I'll just do it myself. :+1:

**Comment by DrWhax** [comment]
Thanks!

**Pull request merged**
