### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by stefansundin**
Move wiki into main repository, for easier pulling. Update documentation based on jduck's contributions.

### CODE REVIEW

**Comment by DrWhax** [comment]
Woops! Somehow I missed this in my email box. Thanks so much!.

**Comment by stefansundin** [comment]
Hmm.. I forgot to add `truecrypt-4.2a-fedora-core-4-x86.tar.gz.sig` and `truecrypt-4.2a-fedora-core-5-x86.tar.gz.sig` to the list of missing files. Could you do that?

**Comment by DrWhax** [comment]
Should these be placed under important or less important?

**Comment by stefansundin** [comment]
I think they are less important.

I consider the source code important because it's the source, and then the windows binaries because that's what almost everyone is using (if there is something shady in the binaries, then it's definitely in the Windows binaries). All the other files are less important according to me (but I still want everything, of course :).

**Comment by DrWhax** [comment]
Cool! See e3e390d

**Comment by DrWhax** [comment]
Err... I mean 02be606

**Comment by stefansundin** [comment]
Great! Thank you.

**Pull request merged**
