### PR TITLE
We don't need a batch script

### PR DESCRIPTION
**Pull request by fraga**
We can verify all files in line with pgp standard command.
Creating linux/mac section.

### CODE REVIEW

**Comment by stefansundin** [comment]
Nice, I did not know about those switches.

However, the output is quite ugly. Looks very machine-readable, and as this page is made for humans with a secondary goal to educate, I'm not sure I want to delete the existing code.

I am willing to complement it, though, maybe something like this:

```
If you want a one-liner, you can try this:
$ gpg --status-fd 1 --verify-files *.sig
```

I changed the --status-fd to 1 so it's easier to pipe. What do you think about that?

**Comment by fraga** [comment]
perfect @stefansundin let me change

**Comment by fraga** [comment]
Let me know if you need further change @stefansundin

**Comment by stefansundin** [comment]
This looks good, thank you!

**Pull request merged**
